### ISSUE TITLE
Merge isValidForm and isValidatingForm

### ISSUE THREAD

**Issue by edgesoft** [cerebral/cerebral-module-forms#2]
@christianalfoni  In the helpers folder isValidForm and isValidatingForm only has one diff on line 12. Maybe we could remove one of them and merge?

**Comment by edgesoft** [comment]
Or pull out the isValidArray as a function.

**Comment by christianalfoni** [comment]
That sounds like a good idea :) Let me add my latest contribution here as well. Pushing it now

**Comment by edgesoft** [comment]
@christianalfoni Just reviewed the code and it is still there. This is not an issue because the code works just fine. Should I close it?

**Comment by abalmos** [comment]
@edgesoft Leave it open. We need to clean it up at some point
