### ISSUE TITLE
How best to do update form

### ISSUE THREAD

**Issue by colinf** [cerebral/cerebral-module-forms#30]
None of the demo projects seems to cover the use case of a form used for updating data, in all cases the 'value' of each field is set when the form is added to state. To make it work I am using code along the following lines in an action when the update form (teamInputForm) is opened:

``` javascript
  const {teams, selectedId} = state.get();
  const {id, name} = teams[selectedId];
  state.set(['teamInputForm', 'id', 'value'], id);
  state.set(['teamInputForm', 'name', 'value'], name);
```

Is this the best way to approach this? I'm happy to contribute an update form example to the demos if anyone can confirm the best approach.

Thanks, Colin

**Comment by colinf** [comment]
One day on & I think my previous post showed some Cerebral naïvety! I now think it's better to instantiate the form and set the state with it once the values are known. So in the same action this is now:

``` javascript
  const {teams, selectedId} = state.get();
  const team = teams[selectedId];
  state.set(['teamInputForm'], makeForm(team));
```

May well still be naïve but it seems to work!

**Comment by edgesoft** [comment]
@colinf Sorry for not answering, have been on holiday 👍 .  When instantiating the form you should do something like 

``` js
teamInputForm: Form({
    name: {
      value: '' // initial state
    },
   id: {
     value: '' // initial state
   }
})
```

You can also use defaultValue for this. Or maybe I understood it wrong?

**Comment by colinf** [comment]
I hope you had a good holiday! Thanks for the response - I think I got there in the end.
