### ISSUE TITLE
Unknown prop `field` on <input> tag

### ISSUE THREAD

**Issue by mephinet** [cerebral/cerebral-module-forms#33]
The `render` function of <Input> passes all its properties on to the <input> element it creates:
https://github.com/cerebral/cerebral-module-forms/blob/master/react/Input/index.js#L31
Thus, also the property `field` will be passed on the the HTML input element, which does not exist there, resulting in the warning:

> Warning: Unknown prop `field` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

**Comment by edgesoft** [comment]
@mephinet Good point! Thanks for the issue!

**Comment by edgesoft** [comment]
Fixed on release 0.3.0
