### ISSUE TITLE
errorMessage for required field.

### ISSUE THREAD

**Issue by kgdev** [cerebral/cerebral-module-forms#5]
Right now there is no way to provide an error message for a required field if it has no valid.

**Comment by abalmos** [comment]
Could pull a "required" error message from `errorMessages` here: 

https://github.com/cerebral/cerebral-module-forms/blob/misc-features/actions/validateRequired.js#L11

and here

https://github.com/cerebral/cerebral-module-forms/blob/misc-features/helpers/configureField.js#L26

**Comment by edgesoft** [comment]
@kgdev You could just use minLength:1

**Comment by kgdev** [comment]
required != minLength:1

If the field is optional and it's empty, it will by pass all the other rules.

**Comment by christianalfoni** [comment]
Yeah, I agree with @abalmos on adding a field for the required error message. Required and validation are two different things really. As required means "no value" and validations means "Value, but invalid value".

So a `requiredMessage` f.ex.

**Comment by edgesoft** [comment]
Sound good!

**Comment by edgesoft** [comment]
@christianalfoni @Guria  Then maybe we can close this issue?

``` js
Form({
  name: {
     isRequired: true,
     value: ''
     requiredMessage: 'Please Fill in the data'
  }
})
```

Later in Component

``` js
renderRequiredMessage(){
  const {form} = this.props;
  // render requiredMessage based on conditions
}
```

**Comment by christianalfoni** [comment]
Yeah, this sounds like a good thing, you want to implement @edgesoft ? :)

**Comment by edgesoft** [comment]
@christianalfoni Do we really need to implement this? When constructing the form just pass requiredMessage as an option, and in the view layer check isTouched?

**Comment by christianalfoni** [comment]
Ah, yeah, sorry... good point :)

**Comment by edgesoft** [comment]
@kgdev I'm closing this. Reopen it again if this approach doesn't work for you.
