### ISSUE TITLE
isValid is inconsistent.

### ISSUE THREAD

**Issue by kgdev** [cerebral/cerebral-module-forms#6]
I think we need a better way to handle isValid.

If a field is not required and has no value, we should not run the validations as all and isValid=true&errorMessage=null.

Otherwise, always run the validations when a field is added or its value is updated.

**Comment by abalmos** [comment]
Looks like this bug is limited to `configureField()`. The signals use 
https://github.com/cerebral/cerebral-module-forms/blob/master/actions/shouldValidate.js#L3
which should be stopping field validations on fields with no value.

**Comment by edgesoft** [comment]
@kgdev Can you verify this again. I have a field that is not required and has no value and I have isValid = true and errorMessage = null.

**Comment by christianalfoni** [comment]
Closing this, feel free to repoen @kgdev :)
